### ISSUE TITLE
TODO 8/28

### ISSUE THREAD

**Issue by shuban-789** [shuban-789/bluefox#6]
- [x] Implement TLS options for connecting and listening
- [ ] Set up an auth mode
- [ ] Potentially service deployment support
